spring:
  application:
    name: headless-crm
  datasource:
    url:  jdbc:postgresql://localhost:5432/headless-crm
    username: headlessCRMAdmin
    password: $HeadlessCRM%1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
application:
  security:
    jwt:
      secret-key: KQ6WdGVpk+hc6d7MS10gZWscvFMnWnvIPvjs1menuCGWYrx61emg6xXQ+mKJTuHpqibj6v7a8jNqGJVHhKpSlA==
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
